local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  origin_x: -2.5
  origin_y: -2.5
  resolution: 0.05
  inflation_radius: 0.25
  min_obstacle_dist: 0.25
  inflation_dist: 0.25
  plugins:
      - {name: obstacle_layer,        type: "costmap_2d::VoxelLayer"}
